"""Utility modules for RLDK.

This package contains utility functions and classes for validation, error handling,
progress indication, and seed management in RLDK.
"""

from .validation import (
    validate_file_exists,
    validate_directory_exists,
    validate_file_extension,
    validate_json_file,
    validate_json_file_with_size_check,
    validate_jsonl_file,
    validate_jsonl_file_streaming,
    validate_dataframe,
    validate_numeric_range,
    validate_string_not_empty,
    validate_choice,
    validate_wandb_uri,
    validate_adapter_type,
    validate_evaluation_suite,
    validate_positive_integer,
    validate_non_negative_integer,
    validate_probability,
    validate_optional_string,
    validate_optional_positive_integer,
    validate_file_size,
    validate_data_quality,
    validate_with_custom_validator,
)

from .error_handling import (
    RLDKError,
    ValidationError,
    AdapterError,
    EvaluationError,
    RLDKTimeoutError,
    format_error_message,
    log_error_with_context,
    validate_file_path,
    sanitize_path,
    validate_data_format,
    validate_required_fields,
    progress_indicator,
    with_retry,
    with_timeout,
    handle_graceful_degradation,
    validate_adapter_source,
    print_usage_examples,
    print_troubleshooting_tips,
    check_dependencies,
    safe_operation,
)

from .progress import (
    ProgressBar,
    Spinner,
    TaskTracker,
    TaskContext,
    progress_bar,
    spinner,
    track_progress,
    timed_operation,
    timed_operation_context,
    estimate_remaining_time,
    format_duration,
    print_operation_status,
    create_progress_callback,
    track_tasks,
    estimate_time_remaining,
    format_time_remaining,
    create_download_progress,
    create_processing_progress,
    create_batch_progress,
    create_validation_progress,
)

from .seed import (
    SeedManager,
    set_global_seed,
    get_current_seed,
    restore_seed_state,
    restore_original_state,
    get_seed_state_summary,
    set_reproducible_environment,
    validate_seed_consistency,
    create_seed_context,
)

__all__ = [
    # Validation utilities
    "validate_file_exists",
    "validate_directory_exists", 
    "validate_file_extension",
    "validate_json_file",
    "validate_json_file_with_size_check",
    "validate_jsonl_file",
    "validate_jsonl_file_streaming",
    "validate_dataframe",
    "validate_numeric_range",
    "validate_string_not_empty",
    "validate_choice",
    "validate_wandb_uri",
    "validate_adapter_type",
    "validate_evaluation_suite",
    "validate_positive_integer",
    "validate_non_negative_integer",
    "validate_probability",
    "validate_optional_string",
    "validate_optional_positive_integer",
    "validate_file_size",
    "validate_data_quality",
    "validate_with_custom_validator",
    
    # Error handling utilities
    "RLDKError",
    "ValidationError",
    "AdapterError", 
    "EvaluationError",
    "RLDKTimeoutError",
    "format_error_message",
    "log_error_with_context",
    "validate_file_path",
    "sanitize_path",
    "validate_data_format",
    "validate_required_fields",
    "progress_indicator",
    "with_retry",
    "with_timeout",
    "handle_graceful_degradation",
    "validate_adapter_source",
    "print_usage_examples",
    "print_troubleshooting_tips",
    "check_dependencies",
    "safe_operation",
    
    # Progress utilities
    "ProgressBar",
    "Spinner",
    "TaskTracker",
    "TaskContext",
    "progress_bar",
    "spinner",
    "track_progress",
    "timed_operation",
    "timed_operation_context",
    "estimate_remaining_time",
    "format_duration",
    "print_operation_status",
    "create_progress_callback",
    "track_tasks",
    "estimate_time_remaining",
    "format_time_remaining",
    "create_download_progress",
    "create_processing_progress",
    "create_batch_progress",
    "create_validation_progress",
    
    # Seed management utilities
    "SeedManager",
    "set_global_seed",
    "get_current_seed",
    "restore_seed_state",
    "restore_original_state",
    "get_seed_state_summary",
    "set_reproducible_environment",
    "validate_seed_consistency",
    "create_seed_context",
]
