"""Adapter for RLDK demo JSONL training logs.

This module provides an adapter for parsing JSONL files generated by the
'rldk demo' command. These files contain synthetic training metrics in a
standardized format suitable for testing and demonstration purposes.

The demo format includes fields like:
- step: Training step number
- reward_mean: Mean reward value
- reward_std: Reward standard deviation
- kl: KL divergence value
- entropy: Entropy value
- loss: Training loss
- policy_grad_norm: Policy gradient norm
- value_grad_norm: Value gradient norm
- advantage_mean: Mean advantage value
- advantage_std: Advantage standard deviation
- pass_rate: Pass rate (for GRPO data)

Example:
    >>> from rldk.adapters.demo_jsonl import DemoJSONLAdapter
    >>> adapter = DemoJSONLAdapter("demo_run_00.jsonl")
    >>> df = adapter.load()
"""

import json
from pathlib import Path
from typing import Dict, Any, List
import pandas as pd

from .base import BaseAdapter


class DemoJSONLAdapter(BaseAdapter):
    """Adapter for RLDK demo JSONL training logs.
    
    This adapter handles JSONL files generated by the 'rldk demo' command.
    It can detect demo format files and convert them to the standard RLDK
    DataFrame format for analysis.
    
    Attributes:
        source: Path to the source file or directory
        
    Example:
        >>> adapter = DemoJSONLAdapter("demo_run_00.jsonl")
        >>> if adapter.can_handle():
        ...     df = adapter.load()
    """

    def can_handle(self) -> bool:
        """Check if source contains RLDK demo JSONL logs."""
        if not self.source.exists():
            return False

        if self.source.is_file():
            return self._is_demo_jsonl_file(self.source)
        elif self.source.is_dir():
            # Check for demo JSONL log files
            jsonl_files = list(self.source.glob("*.jsonl"))
            if len(jsonl_files) > 0:
                # Check if any file looks like demo data
                for file_path in jsonl_files[:3]:  # Check first 3 files
                    if self._is_demo_jsonl_file(file_path):
                        return True
            return False

        return False

    def _is_demo_jsonl_file(self, file_path: Path) -> bool:
        """Check if a file contains RLDK demo JSONL logs."""
        try:
            if file_path.suffix == ".jsonl":
                with open(file_path, "r") as f:
                    first_line = f.readline().strip()
                    if first_line:
                        data = json.loads(first_line)
                        # Check for demo format indicators
                        if isinstance(data, dict):
                            # Demo format has these specific fields
                            demo_fields = [
                                "step", "reward_mean", "reward_std", "kl", 
                                "entropy", "loss", "policy_grad_norm", 
                                "value_grad_norm", "advantage_mean", "advantage_std"
                            ]
                            
                            # Check if it has most of the demo fields
                            has_demo_fields = sum(1 for field in demo_fields if field in data)
                            
                            # Also check for pass_rate (GRPO specific)
                            has_pass_rate = "pass_rate" in data
                            
                            # Must have at least 8 of the core demo fields
                            return has_demo_fields >= 8 or (has_demo_fields >= 6 and has_pass_rate)
                        else:
                            return False
        except (OSError, IOError, json.JSONDecodeError, UnicodeDecodeError, TypeError) as e:
            # Log the specific error for debugging but don't fail the check
            print(f"Warning: Error checking if file {file_path} is demo JSONL format: {e}")
            return False
        return False

    def load(self) -> pd.DataFrame:
        """Load demo JSONL logs and convert to standard format."""
        if not self.can_handle():
            raise ValueError(f"Cannot handle source: {self.source}")

        metrics = []

        if self.source.is_file():
            metrics = self._parse_file(self.source)
        elif self.source.is_dir():
            # Find and parse all demo JSONL log files
            jsonl_files = list(self.source.glob("*.jsonl"))
            for jsonl_file in jsonl_files:
                if self._is_demo_jsonl_file(jsonl_file):
                    metrics.extend(self._parse_file(jsonl_file))

        if not metrics:
            raise ValueError(f"No valid demo JSONL metrics found in {self.source}")

        # Convert to DataFrame
        df = pd.DataFrame(metrics)

        # Ensure required columns exist for the standard format
        required_cols = [
            "step",
            "phase",
            "reward_mean",
            "reward_std",
            "kl_mean",
            "entropy_mean",
            "clip_frac",
            "grad_norm",
            "lr",
            "loss",
            "tokens_in",
            "tokens_out",
            "wall_time",
            "seed",
            "run_id",
            "git_sha",
            "pass_rate",
        ]

        for col in required_cols:
            if col not in df.columns:
                df[col] = None

        return df[required_cols]

    def _parse_file(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse a single demo JSONL log file."""
        metrics = []

        try:
            if file_path.suffix == ".jsonl":
                with open(file_path, "r") as f:
                    for line_num, line in enumerate(f, 1):  # Start line numbering from 1
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            data = json.loads(line)
                            metric = self._extract_demo_metric(data, line_num, file_path)
                            if metric:
                                metrics.append(metric)
                        except json.JSONDecodeError as e:
                            print(f"Warning: JSON decode error in {file_path} at line {line_num}: {e}")
                            continue
        except (OSError, IOError, UnicodeDecodeError) as e:
            print(f"Error parsing {file_path}: {e}")
            # Re-raise the exception with context
            raise RuntimeError(f"Failed to parse demo JSONL file {file_path}: {e}") from e

        return metrics

    def _extract_demo_metric(
        self, data: Dict[str, Any], line_num: int, file_path: Path
    ) -> Dict[str, Any]:
        """Extract metric from demo JSONL format."""
        try:
            # Map demo schema to the expected format
            metric = {
                "step": data.get("step", line_num),
                "phase": "train",  # Demo data is always training
                "reward_mean": data.get("reward_mean"),
                "reward_std": data.get("reward_std"),
                "kl_mean": data.get("kl"),  # Map "kl" to "kl_mean"
                "entropy_mean": data.get("entropy"),  # Map "entropy" to "entropy_mean"
                "clip_frac": None,  # Not in demo data
                "grad_norm": data.get("policy_grad_norm"),  # Use policy grad norm as main grad norm
                "lr": None,  # Not in demo data
                "loss": data.get("loss"),
                "tokens_in": None,  # Not in demo data
                "tokens_out": None,  # Not in demo data
                "wall_time": None,  # Not in demo data
                "seed": 1337,  # Default demo seed
                "run_id": f"demo_{file_path.stem}_{line_num}",
                "git_sha": "demo",
                "pass_rate": data.get("pass_rate", 0.0),  # Include pass_rate for GRPO data
            }

            return metric
        except Exception as e:
            print(f"Error extracting metric from line {line_num}: {e}")
            return None