# Tiny GRPO configuration mirroring the PPO defaults for CPU-only smoke tests.
#
# The metadata fields align with the helper expected by ``examples/run_grpo_tiny.py``
# so the runner can derive trainer configuration and logging paths from YAML alone.
model: sshleifer/tiny-gpt2
dataset_seed: 12
steps: 4
logging_interval: 1
log_path: artifacts/grpo_tiny/run.jsonl
grpo_kwargs:
  run_name: grpo_tiny
  learning_rate: 5.0e-5
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1
  num_train_epochs: 1
  num_generations: 2
  save_steps: 0
  remove_unused_columns: false
  bf16: false
  fp16: false
  dataloader_num_workers: 0
