# Tiny PPO configuration for CPU-friendly smoke runs.
#
# The top-level fields capture metadata that the example runner maps onto the
# TRL ``PPOConfig`` constructor as well as helper settings like log locations.
model: sshleifer/tiny-gpt2
dataset_seed: 8
steps: 4
logging_interval: 1
log_path: artifacts/ppo_tiny/run.jsonl
ppo_kwargs:
  run_name: ppo_tiny
  learning_rate: 5.0e-5
  per_device_train_batch_size: 1
  mini_batch_size: 1
  batch_size: 2
  gradient_accumulation_steps: 1
  num_ppo_epochs: 1
  kl_coef: 0.1
  cliprange: 0.2
  cliprange_value: 0.2
  save_steps: 0
  remove_unused_columns: false
  bf16: false
  fp16: false
  dataloader_num_workers: 0
